name: check-user-repository-class-use
on: [pull_request]

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    name: 'Process changed files'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for UserRepository class use
        run: |
          diff=$(git diff origin/main origin/${GITHUB_HEAD_REF})
          if $(echo "$diff" | (grep -q -E '^\+') | (grep -q -E '(^|\s|\.|\+)UserRepository(\s|$|\(|;)')); then
            echo 'UserRepo usage found'
            exit 1
          fi
